name: flamingo_generator
description: Automatically generate code for converting flamingo JSON by annotating Dart classes.
version: 1.0.0
repository: https://github.com/hukusuke1007/flamingo

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
<<<<<<< HEAD
  analyzer: ^5.2.0
  build: ^2.3.1
  meta: ^1.7.0
  source_gen: ^1.2.3
  flamingo_annotation: 1.0.0
=======
  analyzer: ^4.7.0
  build: ^2.0.1
  meta: ^1.3.0
  source_gen: ^1.0.0
  flamingo_annotation: ^0.5.0
>>>>>>> dea3fe4 (updated dependencies)

dev_dependencies:
  test:
  build_test:
